# Generated by Django 5.1.7 on 2026-01-01 10:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftDeletedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField()),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
