# Generated by Django 5.1.7 on 2026-01-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_softdeleteduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp', models.CharField(max_length=4)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
    ]
